Add support for fallback referrer policies
brokenhandsio/VaporSecurityHeaders pull request #27
Opened 2022-04-13 11:40 UTC by EvanHahn

The `Referrer-Policy` header [supports fallback policies][0]. This adds support for that in this package!

Feel free to reject if this is unwelcome.

[0]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#specify_a_fallback_policy

2022-05-06 18:21 UTC, EvanHahn commented
Let me know if there's anything I can do to help move this along, including telling me that this change is unwelcome.

2022-05-13 13:42 UTC, 0xTim requested changes
Thanks for this! Sorry it's taken me s long to get to it. One stylistic change then good to go

2022-05-13 13:42 UTC, 0xTim commented on Sources/VaporSecurityHeaders/Configurations/ReferrerPolicyConfiguration.swift
> +    private let headerValue: String
I'd prefer to keep the type safety here
```suggestion
    private let options: [Directive]
```

2022-05-13 13:42 UTC, 0xTim commented on Sources/VaporSecurityHeaders/Configurations/ReferrerPolicyConfiguration.swift
> +
This can just save the individual one
```suggestion
    public init(_ directive: Directive) {
        self.directives = [directive]
    }

```

2022-05-13 13:42 UTC, 0xTim commented on Sources/VaporSecurityHeaders/Configurations/ReferrerPolicyConfiguration.swift
> +        headerValue = directives.map({ $0.rawValue }).joined(separator: ", ")
Let's move the String conversion to `setHeader()`
```suggestion
        self.directives = directives
```

2022-05-13 13:42 UTC, 0xTim commented on Sources/VaporSecurityHeaders/Configurations/ReferrerPolicyConfiguration.swift
> +        response.headers.replaceOrAdd(name: .referrerPolicy, value: headerValue)
```suggestion
        response.headers.replaceOrAdd(name: .referrerPolicy, value: directives.map({ $0.rawValue }).joined(separator: ", "))
```

2022-05-13 14:23 UTC, EvanHahn commented
Thanks! I'll plan to respond to these sometime next week.

2022-05-23 12:40 UTC, EvanHahn commented
I haven't forgotten about this. It's still on my list!

2022-05-26 14:37 UTC, EvanHahn commented
Just addressed comments and squashed into a single commit. Thanks for your patience!

2022-05-31 10:06 UTC, 0xTim approved these changes
Thanks!

2022-05-31 10:06 UTC, merged